### ISSUE TITLE
Add Product to Wishlist

### ISSUE THREAD

**Issue by RutujaN01** [RutujaN01/CST438Project2#8]
As a user I want to add products to my wishlist, so that I can save them for future reference or consideration.

- Criteria:
  - Each product page should have an "Add to Wishlist" button.
  - When a product is added to the wishlist, the user should see a confirmation message.
  - Users should be able to view and manage their wishlist (e.g., remove items, categorize items).

**Comment by zliel** [comment]
Closed by #34
